using System;
using System.Collections;

namespace Holo.Virtual.Rooms.Pathfinding
{
    /// <summary>
    /// Represents a set of Coord objects. Together they form the path generated by the DenDribbelaerPathfinder.
    /// </summary>
    public class dribbelaerPath
    {
        #region Declares
        /// <summary>
        /// The coordinates of the path.
        /// </summary>
        internal Stack Coords = new Stack();
        #endregion

        #region Methods
        /// <summary>
        /// Returns the next Coord of the path and removes it from the stack.
        /// </summary>
        internal Coord Pop()
        {
            try { return (Coord)Coords.Pop(); }
            catch { return new Coord(-1, 0); }
        }
        #endregion
    }
}
